"""Build a real multi-speaker meeting fixture from the AMI corpus (CC BY 4.0).

Streams the AMI `ihm` test split (meeting EN2002a), collects the utterances that
fall inside a target time window, and reconstructs a single mixed timeline
(each utterance placed at its meeting timestamp; overlaps summed — real meetings
overlap). Produces a WAV plus a manifest entry with reference speaker turns and
the reference transcript, for validating diarization (#10) and accuracy on real
meeting speech rather than synthetic clips.

Audio under data/benchmark/real/ is gitignored; regenerate with:
    python scripts/fetch_ami_fixture.py
"""
from __future__ import annotations

import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import json
import os
from pathlib import Path

import numpy as np
import soundfile as sf

os.environ.setdefault("HF_HUB_DISABLE_PROGRESS_BARS", "1")
os.environ.setdefault("HF_HUB_DISABLE_SYMLINKS_WARNING", "1")

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "data" / "benchmark" / "real"
TARGET_SR = 16_000

MEETING = "EN2002a"
WIN_START = 300.0    # seconds into the meeting
WIN_END = 420.0      # 120s excerpt
SCAN_CAP = 4000      # max streamed examples to scan for in-window utterances


def main() -> int:
    from datasets import load_dataset

    print(f"Streaming AMI ihm test; collecting {MEETING} [{WIN_START:.0f}-{WIN_END:.0f}s]…")
    ds = load_dataset("edinburghcstr/ami", "ihm", split="test", streaming=True, trust_remote_code=True)

    collected = []  # (begin, end, speaker, text, audio np.float32)
    scanned = 0
    for ex in ds:
        scanned += 1
        if scanned > SCAN_CAP:
            break
        if ex.get("meeting_id") != MEETING:
            continue
        b, e = float(ex["begin_time"]), float(ex["end_time"])
        if b < WIN_START or e > WIN_END:
            continue
        a = ex["audio"]
        arr = np.asarray(a["array"], dtype=np.float32)
        if a["sampling_rate"] != TARGET_SR or arr.size == 0:
            continue
        collected.append((b, e, str(ex["speaker_id"]), str(ex["text"]).strip(), arr))

    if not collected:
        print("No in-window utterances found.", file=sys.stderr)
        return 1
    collected.sort(key=lambda x: x[0])
    print(f"  scanned {scanned} examples; {len(collected)} utterances in window; "
          f"speakers: {sorted(set(c[2] for c in collected))}")

    # Reconstruct a single timeline; place each utterance at its offset, sum overlaps.
    total_samples = int((WIN_END - WIN_START) * TARGET_SR)
    timeline = np.zeros(total_samples, dtype=np.float32)
    turns = []
    transcript_parts = []
    for b, e, spk, text, arr in collected:
        start = int((b - WIN_START) * TARGET_SR)
        end = min(start + len(arr), total_samples)
        if start >= total_samples or end <= start:
            continue
        timeline[start:end] += arr[: end - start]
        turns.append({"speaker": spk, "start": round(b - WIN_START, 3), "end": round(e - WIN_START, 3)})
        if text:
            transcript_parts.append(text)
    # Clip after summing overlaps.
    np.clip(timeline, -1.0, 1.0, out=timeline)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    wav_path = OUT_DIR / f"ami_{MEETING.lower()}_excerpt.wav"
    sf.write(str(wav_path), timeline, TARGET_SR, subtype="PCM_16")

    ground_truth = " ".join(transcript_parts)
    manifest = {
        "_comment": "Real AMI meeting excerpt (CC BY 4.0). Generated by scripts/fetch_ami_fixture.py. Audio gitignored.",
        "fixtures": [
            {
                "id": f"ami_{MEETING.lower()}",
                "path": str(wav_path.relative_to(ROOT)).replace("\\", "/"),
                "language": "en",
                "ground_truth": ground_truth,
                "source": f"AMI {MEETING} [{WIN_START:.0f}-{WIN_END:.0f}s], CC BY 4.0",
                "num_reference_speakers": len(set(t["speaker"] for t in turns)),
                "speaker_turns": turns,
            }
        ],
    }
    (OUT_DIR / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"  wrote {wav_path.relative_to(ROOT)} ({total_samples/TARGET_SR:.0f}s), "
          f"{len(turns)} turns, {len(set(t['speaker'] for t in turns))} speakers")
    print(f"  manifest -> {(OUT_DIR/'manifest.json').relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
